// ─── Case Study Data ───
// Description: Data for 2 main case studies
// Thinksmart Insurance (Marketing) & Dream Talent (Organic + Events)

// ─── Types ───

// Creative work items in gallery
export interface CreativeWorkItem {
  id: string;
  type: "video-thumbnail" | "ad-screenshot";
  thumbnail: string;
  videoUrl?: string;
  caption: string;
  platform?: string;
  metric?: string;
  tag?: string;
}

// Client testimonial
export interface Testimonial {
  quote: string;
  author: string;
  role: string;
  company: string;
  avatar?: string;
}

// Timeline milestone
export interface TimelineMilestone {
  date: string;
  title: string;
  description: string;
  metric?: string;
  type: "start" | "milestone" | "peak";
}

export interface CaseStudySection {
  id: string;
  number: number;
  title: string;
  label?: string;          // Short title for sidebar
  headline: string;        // EN only — Clash Display
  subtitle?: string;       // Sub text below headline
  body: string;
  image?: string;
  imageAlt?: string;
  visualType?: "context" | "context-profile" | "funnel" | "workflow" | "revenue" | "social" | "cpa-challenge" | "product-line";
  bullets?: string[];
  stats?: { label: string; value: string }[];
  closingLine?: string;
  sectionImage?: string;
  sectionImageAlt?: string;
  // Gallery images — dùng cho Dream Talent event sections
  galleryImages?: string[];
  videoUrl?: string;
  videoPoster?: string;
  rewards?: { title: string; image: string }[];
}

export interface CaseStudy {
  id: string;
  company: string;
  tagline: string;
  role: string;
  duration: string;
  description: string;
  color: string;
  website?: string;
  cardImage?: string;
  heroImage?: string;
  highlights: { value: string; label: string; description?: string; image?: string }[];
  sections: CaseStudySection[];
  // Extended fields
  creativeWork?: CreativeWorkItem[];
  testimonial?: Testimonial;
  timeline?: TimelineMilestone[];
  videoUrl?: string;
  videoPoster?: string;
}

// ─── 01. Thinksmart Insurance (Focus: Marketing/Revenue) ───
const thinksmartSections: CaseStudySection[] = [
  {
    id: "thinksmart-context",
    number: 1,
    title: "Context & Challenge",
    label: "01. Context",
    headline: "The Starting Point\n& Challenge",
    subtitle: "ThinkSmart Insurance — Head of Video Production & Media Manager",
    body: "ThinkSmart Insurance had strong sales, but marketing operated without a unified acquisition system. CPA had skyrocketed to $180–$200 while revenue stagnated. My mission was clear: restructure the media operations, drive acquisition costs down, and directly supply Sales with high-converting marketing leads.",
    stats: [
      { label: "CPA in 2022", value: "$180–$200" },
      { label: "Revenue in 2022", value: "$1.8M–$2M" },
      { label: "Mission", value: "CPA ↓ Revenue ↑" },
    ],
  },
  {
    id: "thinksmart-role",
    number: 2,
    title: "My Role & System",
    label: "02. Strategy",
    headline: "Systematic Approach",
    subtitle: "Performance Media Manager — Strategy, Operations & Optimization",
    body: "I built a structured media acquisition machine. My role evolved from simply creating content to architecting a system where every video serves a specific purpose in the acquisition funnel.",
    visualType: "workflow",
    bullets: [
      "Media Team Leadership — Managed the team to adapt massive volumes of ad creatives without losing quality.",
      "100% Sales Supply — The creatives generated by my team successfully supplied 100% of the marketing leads to the Sales department.",
      "Proactive A/B Testing — Worked directly alongside Ads operators to analyze data, optimize creatives, and cut CPA.",
    ],
  },
  {
    id: "thinksmart-product-line",
    number: 3,
    title: "Product Line",
    label: "03. Products",
    headline: "Insurance Product Line",
    subtitle: "Visual Design — IUL, Term Life, EBTP, Kaizen, Max-Funded",
    body: "Designed the full visual identity for ThinkSmart's core insurance product line. Each graphic was crafted to clearly communicate complex financial products — making them approachable and compelling for prospects at every stage of the funnel.",
    visualType: "product-line",
    galleryImages: [
      "/images/02-CaseStudy/thinksmart/05-ProductLine/iul.webp",
      "/images/02-CaseStudy/thinksmart/05-ProductLine/iul-max-funded.webp",
      "/images/02-CaseStudy/thinksmart/05-ProductLine/ebtp.webp",
      "/images/02-CaseStudy/thinksmart/05-ProductLine/kaizen.webp",
      "/images/02-CaseStudy/thinksmart/05-ProductLine/term-life.webp",
    ],
  },
  {
    id: "thinksmart-results",
    number: 4,
    title: "The Results",
    label: "04. Results",
    headline: "Driving Revenue\n& Growth",
    subtitle: "2024 — Achieving the highest company revenue in history",
    body: "Relentless optimization of the creative system directly correlated with decreasing customer acquisition costs and record-breaking revenue peaks.",
    visualType: "cpa-challenge",
    stats: [
      { label: "2024 Revenue Peak", value: "$6.2M" },
      { label: "Marketing Leads Supplied", value: "100%" },
      { label: "CPA Reduction", value: "-66%" },
    ],
    closingLine: "I didn't receive performance commissions. I operated purely on ownership, ensuring my team's output translated directly into tangible business growth.",
  }
];

// ─── Asset Base URL: local khi dev, Supabase khi production ───
const SUPABASE_BASE_URL = "/images/02-CaseStudy/dreamtalent";

// ─── 02. Dream Talent (Focus: Company Events) ───
const dreamTalentSections: CaseStudySection[] = [
  {
    id: "dt-yep",
    number: 1,
    title: "Year End Party",
    headline: "Year End Party",
    subtitle: "Event Planning · Media Coverage · Post-Production",
    body: "Co-organized and directed full media coverage for the annual Year End Party. The goal was to capture authentic moments and the grand scale of the evening without disrupting the attendee experience.",
    videoUrl: `/videos/casestudy/dreamtalent-yep.mp4`,
    videoPoster: `${SUPABASE_BASE_URL}/yep-thumbnail.jpg`,
    galleryImages: [
      `${SUPABASE_BASE_URL}/yep-vdht.jpg`,
      `${SUPABASE_BASE_URL}/yep-luckydraw.jpg`,
      `${SUPABASE_BASE_URL}/yep-vdht2.jpg`,
      `${SUPABASE_BASE_URL}/yep-1-v2.png`,
      `${SUPABASE_BASE_URL}/yep-2-v2.png`,
      `${SUPABASE_BASE_URL}/yep-3-v2.png`,
      `${SUPABASE_BASE_URL}/yep-4-v2.png`,
      `${SUPABASE_BASE_URL}/yep-polaroid-1.png`,
      `${SUPABASE_BASE_URL}/yep-polaroid-2-new.jpg`,
    ],
    rewards: [
      { title: "Grand Prize: 5M VNĐ", image: `${SUPABASE_BASE_URL}/rewards/v-5m.jpg` },
      { title: "First Prize: 3M VNĐ", image: `${SUPABASE_BASE_URL}/rewards/v-3m.jpg` },
      { title: "Second Prize: 2M VNĐ", image: `${SUPABASE_BASE_URL}/rewards/v-2m.jpg` },
      { title: "Third Prize: 1.5M VNĐ", image: `${SUPABASE_BASE_URL}/rewards/v-1.5m.jpg` },
      { title: "Incentive: 1M VNĐ", image: `${SUPABASE_BASE_URL}/rewards/v-1m.jpg` },
      { title: "Incentive: 800K VNĐ", image: `${SUPABASE_BASE_URL}/rewards/v-800k.jpg` },
      { title: "Incentive: 500K VNĐ", image: `${SUPABASE_BASE_URL}/rewards/v-500k.jpg` },
      { title: "Special: Yacht Trip", image: `${SUPABASE_BASE_URL}/rewards/v-yacht.jpg` },
      { title: "Luxury Dinner", image: `${SUPABASE_BASE_URL}/rewards/v-dinner.jpg` },
      { title: "Full Day Off", image: `${SUPABASE_BASE_URL}/rewards/v-day-off.jpg` },
      { title: "1H Early Leave", image: `${SUPABASE_BASE_URL}/rewards/v-early.jpg` },
      { title: "1H Late Arrival", image: `${SUPABASE_BASE_URL}/rewards/v-late.jpg` },
      { title: "30 Min Break", image: `${SUPABASE_BASE_URL}/rewards/v-30min.jpg` },
      { title: "Uniform Gift", image: `${SUPABASE_BASE_URL}/rewards/v-uniform.jpg` },
      { title: "TIS Special Reward 1", image: `${SUPABASE_BASE_URL}/rewards/v-tis-1.jpg` },
      { title: "TIS Special Reward 2", image: `${SUPABASE_BASE_URL}/rewards/v-tis-2.jpg` },
    ],
  },
  {
    id: "dt-teambuilding",
    number: 2,
    title: "Team Building",
    headline: "Team Building",
    subtitle: "Action Photography · Highlight Videos · Internal Media",
    body: "Captured high-energy team building activities with a focus on authentic moments. Delivered short-form recap videos and photo collections that reinforced team culture and morale.",
    galleryImages: [
      `${SUPABASE_BASE_URL}/teambuilding/DHAI0036.webp`,
      `${SUPABASE_BASE_URL}/teambuilding/DHAI0474.webp`,
      `${SUPABASE_BASE_URL}/teambuilding/DHAI0483.webp`,
      `${SUPABASE_BASE_URL}/teambuilding/DHAI1164.webp`,
      `${SUPABASE_BASE_URL}/teambuilding/DHAI1559.webp`,
      `${SUPABASE_BASE_URL}/teambuilding/flycam-3.webp`,
      `${SUPABASE_BASE_URL}/teambuilding/flycam-8.webp`,
      `${SUPABASE_BASE_URL}/teambuilding/DRT-FLYCAM-12.webp`,
      `${SUPABASE_BASE_URL}/teambuilding/DRT-FLYCAM-26.webp`,
      `${SUPABASE_BASE_URL}/teambuilding/DRT-FLYCAM-27.webp`
    ],
  },
  {
    id: "dt-sportsday",
    number: 3,
    title: "Hội thao (Sports Day)",
    headline: "Company Sports Day",
    subtitle: "Dynamic Sports Coverage · Highlight Reels · Team Spirit",
    body: "Directed highly dynamic sports coverage for the annual corporate Sports Day. The focus was on freezing peak action, capturing raw emotion, and showcasing the competitive yet bonded spirit of the company.",
    galleryImages: [
      `${SUPABASE_BASE_URL}/sportsday/sports-1.jpg`,
      `${SUPABASE_BASE_URL}/sportsday/sports-2.jpg`,
      `${SUPABASE_BASE_URL}/sportsday/sports-3.jpg`,
      `${SUPABASE_BASE_URL}/sportsday/sports-4.jpg`,
      `${SUPABASE_BASE_URL}/sportsday/sports-5.jpg`,
      `${SUPABASE_BASE_URL}/sportsday/sports-6.jpg`,
      `${SUPABASE_BASE_URL}/sportsday/sports-7.jpg`,
      `${SUPABASE_BASE_URL}/sportsday/sports-8.jpg`,
      `${SUPABASE_BASE_URL}/sportsday/sports-9.jpg`,
      `${SUPABASE_BASE_URL}/sportsday/sports-10.jpg`,
      `${SUPABASE_BASE_URL}/sportsday/sports-11.jpg`,
    ],
  },
];

// ─── Case Studies Array ───
export const caseStudies: CaseStudy[] = [
  {
    id: "thinksmart",
    company: "Thinksmart Insurance",
    tagline: "Generating 100% of marketing leads for Sales",
    role: "Head of Video Production / Performance Media Manager",
    duration: "2023 — Present",
    description: "Proactively built and managed a high-volume performance media pipeline. Supplied 100% of marketing leads through relentless A/B testing, rapid creative adaptation, and deep involvement in ad strategy.",
    color: "#FF4000",
    website: "https://thinksmartinsurance.com/en/home",
    cardImage: "/images/02-CaseStudy/thinksmart/01-Hero/card-cover.webp",
    heroImage: "/images/02-CaseStudy/thinksmart/01-Hero/banner-01.webp",
    highlights: [
      { value: "$6,200,000", label: "2024 Revenue Peak", description: "Contributed to the highest corporate revenue in history through constant creative optimization.", image: "/images/02-CaseStudy/thinksmart/04-Results/revenue-hero.webp" },
      { value: "100%", label: "Leads Sourced", description: "My team's adapted videos became the supreme driver, providing 100% of marketing leads for Sales." },
      { value: "Proactive", label: "A/B Testing", description: "Operated with extreme ownership. Actively worked with Ads team to rapidly fix and scale creatives." },
    ],
    sections: thinksmartSections,
    timeline: [
      { date: "2022", title: "Media Foundation", description: "Established initial video operational frameworks.", type: "start" },
      { date: "2023", title: "Media Team Lead", description: "Promoted to lead the entire design and video production squad.", type: "milestone" },
      { date: "2024", title: "Record Historic Revenue & Leads", description: "Hit $6,200,000 in revenue by driving 100% of the marketing leads to Sales through scaled A/B testing.", metric: "$6.2M", type: "peak" },
    ],
  },
  {
    id: "dreamtalent",
    company: "Dream Talent",
    tagline: "Corporate event media planning & production",
    role: "Event Media Director",
    duration: "2022 — 2023",
    description: "Led full creative direction for Dream Talent's corporate media — from concept to final delivery across recruitment films, company profiles, and internal showcases.",
    color: "#e8512d",
    website: "https://dreamtalent.com.vn/",
    cardImage: `${SUPABASE_BASE_URL}/dreamtalent_card.png`,
    heroImage: `${SUPABASE_BASE_URL}/dreamtalent-poster.jpg`,
    videoUrl: `${SUPABASE_BASE_URL}/dreamtalent-video.mp4`,
    videoPoster: `${SUPABASE_BASE_URL}/dreamtalent-poster.jpg`,
    highlights: [
      { value: "Full", label: "Media Scale", description: "Directed complete photo/video coverage for the largest annual gatherings (YEP & Team Building)." },
      { value: "100%", label: "In-house Execution", description: "Managed the entire pipeline: pre-event planning, multi-cam shooting, and post-production." },
      { value: "48 Hrs", label: "Rapid Turnaround", description: "Delivered fully graded cinematic highlight reels within 2 days to maximize internal engagement." },
    ],
    sections: dreamTalentSections,
    creativeWork: [
      // Placeholders for Event videos/images so recruiters can click them.
      {
        id: "yep-video-1",
        type: "video-thumbnail",
        thumbnail: "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?q=80&w=800&auto=format&fit=crop",
        caption: "Year End Party Highlight Reel",
        platform: "Internal",
        tag: "Event",
      },
      {
        id: "tb-video-1",
        type: "video-thumbnail",
        thumbnail: "https://images.unsplash.com/photo-1528605248644-14dd04022da1?q=80&w=800&auto=format&fit=crop",
        caption: "Annual Team Building Recap",
        platform: "Internal",
        tag: "Event",
      }
    ]
  }
];

// ─── Section heading ───
export const caseStudyHeading = {
  overline: "CASE STUDIES",
  title: "Selected Stories",
  description: "Explore how I drive real business impact and build strong company culture through creative video strategy.",
};
