// ─── Case Study Data ───
// Description: Data for 2 main case studies
// Thinksmart Insurance (Marketing) & Dream Talent (Organic + Events)

// ─── Types ───

// Creative work items in gallery
export interface CreativeWorkItem {
  id: string;
  type: "video-thumbnail" | "ad-screenshot";
  thumbnail: string;
  videoUrl?: string;
  caption: string;
  platform?: string;
  metric?: string;
  tag?: string;
}

// Client testimonial
export interface Testimonial {
  quote: string;
  author: string;
  role: string;
  company: string;
  avatar?: string;
}

// Timeline milestone
export interface TimelineMilestone {
  date: string;
  title: string;
  description: string;
  metric?: string;
  type: "start" | "milestone" | "peak";
}

export interface CaseStudySection {
  id: string;
  number: number;
  title: string;
  headline: string;        // EN only — Clash Display
  subtitle?: string;       // Sub text below headline
  body: string;
  image?: string;
  imageAlt?: string;
  visualType?: "context" | "context-profile" | "funnel" | "workflow" | "revenue" | "social" | "cpa-challenge";
  bullets?: string[];
  stats?: { label: string; value: string }[];
  closingLine?: string;
  sectionImage?: string;
  sectionImageAlt?: string;
  // Gallery images — dùng cho Dream Talent event sections
  galleryImages?: string[];
  videoUrl?: string;
  videoPoster?: string;
  rewards?: { title: string; image: string }[];
}

export interface CaseStudy {
  id: string;
  company: string;
  tagline: string;
  role: string;
  duration: string;
  description: string;
  color: string;
  website?: string;
  cardImage?: string;
  heroImage?: string;
  highlights: { value: string; label: string; description?: string; image?: string }[];
  sections: CaseStudySection[];
  // Extended fields
  creativeWork?: CreativeWorkItem[];
  testimonial?: Testimonial;
  timeline?: TimelineMilestone[];
}

// ─── 01. Thinksmart Insurance (Focus: Marketing/Revenue) ───
const thinksmartSections: CaseStudySection[] = [
  {
    id: "thinksmart-context",
    number: 1,
    title: "Context & Challenge",
    headline: "The Starting Point\n& Challenge",
    subtitle: "ThinkSmart Insurance — Head of Video Production & Media Manager",
    body: "ThinkSmart Insurance had strong sales, but marketing operated without a unified acquisition system. CPA had skyrocketed to $180–$200 while revenue stagnated. My mission was clear: restructure the media operations, drive acquisition costs down, and directly supply Sales with high-converting marketing leads.",
    visualType: "context",
    stats: [
      { label: "CPA in 2022", value: "$180–$200" },
      { label: "Revenue in 2022", value: "$1.8M–$2M" },
      { label: "Mission", value: "CPA ↓ Revenue ↑" },
    ],
  },
  {
    id: "thinksmart-role",
    number: 2,
    title: "My Role & System",
    headline: "Building a\nPerformance System",
    subtitle: "Performance Media Manager — Strategy, Operations & Optimization",
    body: "I took full ownership of the Media team, transforming it from a standard production unit into a ruthless performance engine. We proactively collaborated with the Ads team, ensuring our video adaptations met extreme volume and quality demands. When A/B tests ran, we instantly jumped in to fix and iterate underperforming creatives.",
    visualType: "workflow",
    bullets: [
      "Media Team Leadership — Managed the team to adapt massive volumes of ad creatives without losing quality.",
      "100% Sales Supply — The creatives generated by my team successfully supplied 100% of the marketing leads to the Sales department.",
      "Proactive A/B Testing — Worked directly alongside Ads operators to analyze data, optimize creatives, and cut CPA.",
    ],
  },
  {
    id: "thinksmart-results",
    number: 3,
    title: "The Results",
    headline: "Driving Revenue\n& Growth",
    subtitle: "2024 — Achieving the highest company revenue in history",
    body: "Through sheer creative volume and relentless optimization, our media pipeline fed directly into the company's bottom line. The result was the highest revenue peak the company had ever seen while I was there.",
    visualType: "revenue",
    stats: [
      { label: "2024 Revenue Peak", value: "$6,000,000" },
      { label: "Marketing Leads Supplied", value: "100%" },
      { label: "CPA Reduction", value: "-44%" },
    ],
    closingLine: "I didn't receive performance commissions. I operated purely on ownership, ensuring my team's output translated directly into tangible business growth.",
  }
];

// ─── 02. Dream Talent (Focus: Company Events) ───
const dreamTalentSections: CaseStudySection[] = [
  {
    id: "dt-yep",
    number: 1,
    title: "Year End Party",
    headline: "Year End\nParty",
    subtitle: "Event Planning · Media Coverage · Post-Production",
    body: "Co-organized and directed full media coverage for the annual Year End Party. The goal was to capture authentic moments and the grand scale of the evening without disrupting the attendee experience.",
    videoUrl: "/videos/casestudy/dreamtalent-yep.mp4",
    videoPoster: "/images/casestudy/dreamtalent/yep-thumbnail.jpg",
    galleryImages: [
      "/images/casestudy/dreamtalent/yep-vdht.jpg",
      "/images/casestudy/dreamtalent/yep-luckydraw.jpg",
      "/images/casestudy/dreamtalent/yep-vdht2.jpg",
      "/images/casestudy/dreamtalent/yep-1-v2.png",
      "/images/casestudy/dreamtalent/yep-2-v2.png",
      "/images/casestudy/dreamtalent/yep-3-v2.png",
      "/images/casestudy/dreamtalent/yep-4-v2.png",
      "/images/casestudy/dreamtalent/yep-polaroid-1.png",
      "/images/casestudy/dreamtalent/yep-polaroid-2-new.jpg",
    ],
    rewards: [
      { title: "Grand Prize: 5M VNĐ", image: "/images/casestudy/dreamtalent/rewards/v-5m.jpg" },
      { title: "First Prize: 3M VNĐ", image: "/images/casestudy/dreamtalent/rewards/v-3m.jpg" },
      { title: "Second Prize: 2M VNĐ", image: "/images/casestudy/dreamtalent/rewards/v-2m.jpg" },
      { title: "Third Prize: 1.5M VNĐ", image: "/images/casestudy/dreamtalent/rewards/v-1.5m.jpg" },
      { title: "Incentive: 1M VNĐ", image: "/images/casestudy/dreamtalent/rewards/v-1m.jpg" },
      { title: "Incentive: 800K VNĐ", image: "/images/casestudy/dreamtalent/rewards/v-800k.jpg" },
      { title: "Incentive: 500K VNĐ", image: "/images/casestudy/dreamtalent/rewards/v-500k.jpg" },
      { title: "Special: Yacht Trip", image: "/images/casestudy/dreamtalent/rewards/v-yacht.jpg" },
      { title: "Luxury Dinner", image: "/images/casestudy/dreamtalent/rewards/v-dinner.jpg" },
      { title: "Full Day Off", image: "/images/casestudy/dreamtalent/rewards/v-day-off.jpg" },
      { title: "1H Early Leave", image: "/images/casestudy/dreamtalent/rewards/v-early.jpg" },
      { title: "1H Late Arrival", image: "/images/casestudy/dreamtalent/rewards/v-late.jpg" },
      { title: "30 Min Break", image: "/images/casestudy/dreamtalent/rewards/v-30min.jpg" },
      { title: "Uniform Gift", image: "/images/casestudy/dreamtalent/rewards/v-uniform.jpg" },
      { title: "TIS Special Reward 1", image: "/images/casestudy/dreamtalent/rewards/v-tis-1.jpg" },
      { title: "TIS Special Reward 2", image: "/images/casestudy/dreamtalent/rewards/v-tis-2.jpg" },
    ],
  },
  {
    id: "dt-teambuilding",
    number: 2,
    title: "Team Building",
    headline: "Team\nBuilding",
    subtitle: "Action Photography · Highlight Videos · Internal Media",
    body: "Captured high-energy team building activities with a focus on authentic moments. Delivered short-form recap videos and photo collections that reinforced team culture and morale.",
    galleryImages: [
      "/images/casestudy/dreamtalent/tb-1.png",
      "/images/casestudy/dreamtalent/tb-2.png",
      "/images/casestudy/dreamtalent/tb-3.png",
      "https://images.unsplash.com/photo-1522071820081-009f0129c71c?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1520333789090-1afc82db536a?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1544391682-17dd1d84a38d?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1517457373958-b7bdd4587205?q=80&w=1200&auto=format&fit=crop",
    ],
  },
  {
    id: "dt-sportsday",
    number: 3,
    title: "Hội thao (Sports Day)",
    headline: "Company\nSports Day",
    subtitle: "Dynamic Sports Coverage · Highlight Reels · Team Spirit",
    body: "Directed highly dynamic sports coverage for the annual corporate Sports Day. The focus was on freezing peak action, capturing raw emotion, and showcasing the competitive yet bonded spirit of the company.",
    galleryImages: [
      "https://images.unsplash.com/photo-1526676037598-3317e666ed1b?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1551632811-561732d1e306?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1461896836934-ffe607ba8211?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1530549387789-4c1017266635?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1541252260730-0412e8e2108e?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1461896836934-ffe607ba8211?q=80&w=1200&auto=format&fit=crop",
    ],
  },
];

// ─── Case Studies Array ───
export const caseStudies: CaseStudy[] = [
  {
    id: "thinksmart",
    company: "Thinksmart Insurance",
    tagline: "Generating 100% of marketing leads for Sales",
    role: "Head of Video Production / Performance Media Manager",
    duration: "2023 — Present",
    description: "Proactively built and managed a high-volume performance media pipeline. Supplied 100% of marketing leads through relentless A/B testing, rapid creative adaptation, and deep involvement in ad strategy.",
    color: "#FF4000",
    website: "https://thinksmartinsurance.com/en/home",
    cardImage: "/images/casestudy/thinksmart/card-cover.png",
    heroImage: "/images/casestudy/thinksmart/HeroCaseStudy.png",
    highlights: [
      { value: "$6,000,000", label: "2024 Revenue Peak", description: "Contributed to the highest corporate revenue in history through constant creative optimization.", image: "/images/casestudy/thinksmart/revenue-hero.png" },
      { value: "100%", label: "Leads Sourced", description: "My team's adapted videos became the supreme driver, providing 100% of marketing leads for Sales." },
      { value: "Proactive", label: "A/B Testing", description: "Operated with extreme ownership. Actively worked with Ads team to rapidly fix and scale creatives." },
    ],
    sections: thinksmartSections,
    timeline: [
      { date: "2022", title: "Media Foundation", description: "Established initial video operational frameworks.", type: "start" },
      { date: "2023", title: "Media Team Lead", description: "Promoted to lead the entire design and video production squad.", type: "milestone" },
      { date: "2024", title: "Record Historic Revenue & Leads", description: "Hit $6,000,000 in revenue by driving 100% of the marketing leads to Sales through scaled A/B testing.", metric: "$6.0M", type: "peak" },
    ],
    creativeWork: []
  },
  {
    id: "dreamtalent",
    company: "Dream Talent",
    tagline: "Corporate event media planning & production",
    role: "Event Media Director",
    duration: "2022 — 2023",
    description: "Led the end-to-end media production for Dream Talent's major corporate events. The priority was capturing high-energy, authentic moments and delivering cinematic highlight reels with extremely rapid turnarounds.",
    color: "#e8512d",
    website: "https://dreamtalent.com.vn/",
    cardImage: "/images/casestudy/dreamtalent/dreamtalent_card.png",
    heroImage: "/images/casestudy/dreamtalent/dreamtalent_hero.png",
    highlights: [
      { value: "Full", label: "Media Scale", description: "Directed complete photo/video coverage for the largest annual gatherings (YEP & Team Building)." },
      { value: "100%", label: "In-house Execution", description: "Managed the entire pipeline: pre-event planning, multi-cam shooting, and post-production." },
      { value: "48 Hrs", label: "Rapid Turnaround", description: "Delivered fully graded cinematic highlight reels within 2 days to maximize internal engagement." },
    ],
    sections: dreamTalentSections,
    creativeWork: [
      // Placeholders for Event videos/images so recruiters can click them.
      {
        id: "yep-video-1",
        type: "video-thumbnail",
        thumbnail: "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?q=80&w=800&auto=format&fit=crop",
        caption: "Year End Party Highlight Reel",
        platform: "Internal",
        tag: "Event",
      },
      {
        id: "tb-video-1",
        type: "video-thumbnail",
        thumbnail: "https://images.unsplash.com/photo-1528605248644-14dd04022da1?q=80&w=800&auto=format&fit=crop",
        caption: "Annual Team Building Recap",
        platform: "Internal",
        tag: "Event",
      }
    ]
  }
];

// ─── Section heading ───
export const caseStudyHeading = {
  overline: "CASE STUDIES",
  title: "Proven Results",
  description: "Explore how I drive real business impact and build strong company culture through creative video strategy.",
};
